spring.application.name=BoatSafariManagement

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=BoatSafariManagement;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.boatadmin=INFO
logging.level.org.springframework.web=DEBUG
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# Enable detailed error messages
server.error.include-stacktrace=always
server.error.include-message=always

# Application Configuration (NEW - For Singleton Pattern)
app.report.default-days=30
app.pagination.page-size=10
app.security.session-timeout=1800
app.feature.reports.enabled=true
app.feature.maintenance.enabled=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fzaslam.45@gmail.com
spring.mail.password=qeqffnnigefyceci
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
